

server {                                                      
    listen       80;                                                             
    listen  [::]:80;                                                             
    server_name  localhost;                                                      
                                                                                 
    #access_log  /var/log/nginx/host.access.log  main;                           
                                                                                 
    location / {                                                                 
        root   /usr/share/nginx/html;  

        # 
        # ENABLE FOLDER LISTING
        #
        autoindex on;                                          
    }                                                                            

    # used for testing purposes (CI)
    location = /___test__me_fooo_boo {
        return 200 "foo-boo-ok-test-response";
        add_header Content-Type text/plain;
    }

    # deny access to .htaccess files, if Apache's document root                  
    # concurs with nginx's one                                                   
    #                                                                            
    #location ~ /\.ht {                                                          
    #    deny  all;                                                              
    #}                                                                           
} 
