

server {                                                      
    listen       80;                                                             
    listen  [::]:80;                                                             
    server_name  localhost;                                                      
                                                                                 
    #access_log  /var/log/nginx/host.access.log  main;                           
                                                                                 
    location / {                                                                 
        root   /usr/share/nginx/html;  

        index index.html;
        client_max_body_size 35m;
        error_page 405 =200 $uri;
        access_log off;
        gzip off; 
        fastcgi_read_timeout 999;
        log_not_found off;
        server_tokens off;
        tcp_nodelay on;
        tcp_nopush on;
        sendfile on;
        open_file_cache max=200000 inactive=20s;
        open_file_cache_valid 30s;
        open_file_cache_min_uses 2;
        open_file_cache_errors off;

        # 
        # ENABLE FOLDER LISTING
        #
        autoindex on;                                          
    }                                                                            

    # used for testing purposes (CI)
    location = /___test__me_fooo_boo {
        return 200 "foo-boo-ok-test-response";
        add_header Content-Type text/plain;
    }

    # deny access to .htaccess files, if Apache's document root                  
    # concurs with nginx's one                                                   
    #                                                                            
    #location ~ /\.ht {                                                          
    #    deny  all;                                                              
    #}                                                                           
} 
