---
name: 'Docker build and push'

on:
  workflow_dispatch:
  push:
    branches: [master, '*']

jobs:
  tooling_docker_build_and_push:
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/build_and_push_image.yml@main
    with:
      docker_build_context: "tooling"
      docker_build_file: "tooling/Dockerfile"
      docker_latest_tag: "tooling"
      push_enabled: true
      # push_destinations: ghcr.io;dockerhub
      push_destinations: dockerhub
      # ghcr_repo_owner: ${{ github.repository_owner }}
      # ghcr_repo: ${{ github.repository }}
      dockerhub_profile: eritikass
      dockerhub_repo: tooling
      get_version_method: git_commit_hash_short
    secrets:
      # ghcr_token: ${{ secrets.GITHUB_TOKEN }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}


  nginx_dir_listing_docker_build_and_push:
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/build_and_push_image.yml@main
    with:
      docker_build_context: "nginx-dir-listing"
      docker_build_file: "nginx-dir-listing/Dockerfile"
      docker_latest_tag: "nginx-dir-listing"
      push_enabled: true
      # push_destinations: ghcr.io;dockerhub
      push_destinations: dockerhub
      # ghcr_repo_owner: ${{ github.repository_owner }}
      # ghcr_repo: ${{ github.repository }}
      dockerhub_profile: eritikass
      dockerhub_repo: tooling
      get_version_method: git_commit_hash_short
    secrets:
      # ghcr_token: ${{ secrets.GITHUB_TOKEN }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}