---
name: ci

on:
  workflow_dispatch:

jobs:
  build_and_push:
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/build_and_push_image.yml@main
    with:
      push_enabled: true
      ghcr_repo_owner: ${{ github.repository_owner }}
      ghcr_repo: ${{ github.repository }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
