---
name: 'Docker build and push'

on:
  workflow_dispatch:
  push:
    branches: [master, '*']

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: uname -m
  
      - name: Test nginx-dir-listing image (nginx.config)
        run: |
          set -xe
          cd ./nginx-dir-listing
          docker build -t nginx-dir-listing .
          echo "test-me-123" > /tmp/test-me-123.txt
          docker run --rm -d -p 80:80 -v "/tmp/test-me-123.txt:/usr/share/nginx/html/test-me-123.txt" nginx-dir-listing
          docker images
          sleep 5

          curl -v -f http://localhost:80/test-me-123.txt || exit 1
          output_test_me_123_txt=$(curl -s http://localhost:80/test-me-123.txt) 
          if [[ "$output_test_me_123_txt" != "test-me-123" ]]; then
            echo -e "\nTest failed(test-me-123.txt): $output_test_me_123_txt"
            exit 1
          fi
          echo -e "\nTest passed(test-me-123.txt): '$output_test_me_123_txt'"

          # test listing works
          curl -v -f http://localhost:80/ || exit 1
          output_dir_listing=$(curl -s http://localhost:80/)
          if [[ "$output_dir_listing" != *"test-me-123.txt"* ]]; then
            echo -e "\nTest failed(dir-listing): $output_dir_listing"
            exit 1
          fi
          echo -e "\nTest passed(dir-listing): '$output_dir_listing'"


          # openspeedtest upload handler
          curl -v http://localhost:80/openspeedtest/upload
          curl -f http://localhost:80/openspeedtest/upload || exit 1

          docker ps -a 

      - name: Test tooling image

        run: |
          set -xe
          cd ./tooling
          docker build -t tooling-image .
          docker images
          # run some test commands
          docker run --rm -it tooling-image date
          docker run --rm -it tooling-image sh -c 'uname -m'
          docker run --rm -it tooling-image bash -c 'gojq --version'
          docker run --rm -it tooling-image yq_v4 --version


  tooling_docker_build_and_push:
    needs: test_job
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/build_and_push_image.yml@main
    with:
      docker_build_context: "tooling"
      docker_build_file: "tooling/Dockerfile"
      docker_latest_tag: "tooling"
      push_enabled: true
      # push_destinations: ghcr.io;dockerhub
      push_destinations: dockerhub
      # ghcr_repo_owner: ${{ github.repository_owner }}
      # ghcr_repo: ${{ github.repository }}
      dockerhub_profile: eritikass
      dockerhub_repo: tooling
      get_version_method: git_commit_hash_short
    secrets:
      # ghcr_token: ${{ secrets.GITHUB_TOKEN }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}


  nginx_dir_listing_docker_build_and_push:
    needs: test_job
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/build_and_push_image.yml@main
    with:
      docker_build_context: "nginx-dir-listing"
      docker_build_file: "nginx-dir-listing/Dockerfile"
      docker_latest_tag: "nginx-dir-listing"
      push_enabled: true
      # push_destinations: ghcr.io;dockerhub
      push_destinations: dockerhub
      # ghcr_repo_owner: ${{ github.repository_owner }}
      # ghcr_repo: ${{ github.repository }}
      dockerhub_profile: eritikass
      dockerhub_repo: tooling
      get_version_method: git_commit_hash_short
    secrets:
      # ghcr_token: ${{ secrets.GITHUB_TOKEN }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
